# Generated by Django 2.0.2 on 2018-03-27 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bucketlist',
            old_name='name',
            new_name='deseo',
        ),
        migrations.RenameField(
            model_name='bucketlist',
            old_name='owner',
            new_name='dueño',
        ),
        migrations.RenameField(
            model_name='bucketlist',
            old_name='date_created',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='bucketlist',
            old_name='date_modified',
            new_name='fecha_modificacion',
        ),
    ]
